# PNPM Workspace Configuration for Infinder
# This file defines the workspace structure for the Infinder platform
# Each package listed here can be managed independently while sharing dependencies

packages:
  # React frontend application with Vite build tool (Infinder)
  - client
  # Express.js backend server with API endpoints (Infinder)
  - server 