# PNPM Workspace Configuration for New Design
# This file defines the workspace structure for the new design iteration
# Each package listed here can be managed independently while sharing dependencies

packages:
  # React frontend application with Vite build tool (New Design)
  - client
  # Express.js backend server with API endpoints (New Design)
  - server 